[package]
name = "frost-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true
build = "build.rs"

[[bin]]
name = "frost-desktop"
path = "src/main.rs"

[dependencies]
frost-chat = { path = "../frost-chat" }
serde_json = { workspace = true }

[build-dependencies]
cc = "1"
